name: manufacturing
channels:
  - defaults
dependencies:
  - ca-certificates=2019.1.23=0
  - certifi=2018.11.29=py36_0
  - libcxx=4.0.1=hcfea43d_1
  - libcxxabi=4.0.1=hcfea43d_1
  - libedit=3.1.20181209=hb402a30_0
  - libffi=3.2.1=h475c297_4
  - ncurses=6.1=h0a44026_1
  - openssl=1.0.2p=h1de35cc_0
  - pip=19.0.1=py36_0
  - python=3.6.2=hd04bb42_19
  - readline=7.0=h1de35cc_5
  - setuptools=40.7.3=py36_0
  - sqlite=3.26.0=ha441bb4_0
  - tk=8.6.8=ha441bb4_0
  - wheel=0.32.3=py36_0
  - xz=5.2.4=h1de35cc_4
  - zlib=1.2.11=h1de35cc_3
  - pip:
    - absl-py==0.7.0
    - adal==1.2.1
    - applicationinsights==0.11.7
    - appnope==0.1.0
    - asn1crypto==0.24.0
    - astor==0.7.1
    - astroid==2.1.0
    - azure-common==1.1.18
    - azure-graphrbac==0.53.0
    - azure-mgmt-authorization==0.51.1
    - azure-mgmt-containerregistry==2.7.0
    - azure-mgmt-keyvault==1.1.0
    - azure-mgmt-nspkg==3.0.2
    - azure-mgmt-resource==2.1.0
    - azure-mgmt-storage==3.1.1
    - azure-nspkg==3.0.2
    - azure-storage-blob==1.4.0
    - azure-storage-common==1.4.0
    - azure-storage-nspkg==3.1.0
    - azureml-contrib-iot==1.0.10
    - azureml-contrib-services==1.0.10
    - azureml-core==1.0.10
    - azureml-pipeline==1.0.10
    - azureml-pipeline-core==1.0.10
    - azureml-pipeline-steps==1.0.10.1
    - azureml-sdk==1.0.10
    - azureml-telemetry==1.0.10
    - azureml-train==1.0.10
    - azureml-train-core==1.0.10
    - azureml-train-restclients-hyperdrive==1.0.10
    - backcall==0.1.0
    - backports.tempfile==1.0
    - backports.weakref==1.0.post1
    - bcrypt==3.1.6
    - bleach==3.1.0
    - cffi==1.11.5
    - chardet==3.0.4
    - click==7.0
    - colorama==0.4.1
    - contextlib2==0.5.5
    - cryptography==2.5
    - cycler==0.10.0
    - decorator==4.3.2
    - defusedxml==0.5.0
    - docker==3.7.0
    - docker-pycreds==0.4.0
    - entrypoints==0.3
    - flask==1.0.2
    - gast==0.2.2
    - grpcio==1.18.0
    - idna==2.8
    - ipykernel==5.1.0
    - ipython==7.2.0
    - ipython-genutils==0.2.0
    - ipywidgets==7.4.2
    - isodate==0.6.0
    - isort==4.3.4
    - itsdangerous==1.1.0
    - jedi==0.13.2
    - jinja2==2.10
    - jmespath==0.9.3
    - jsonpickle==1.1
    - jsonschema==2.6.0
    - jupyter==1.0.0
    - jupyter-client==5.2.4
    - jupyter-console==6.0.0
    - jupyter-core==4.4.0
    - kiwisolver==1.0.1
    - lazy-object-proxy==1.3.1
    - markdown==3.0.1
    - markupsafe==1.1.0
    - matplotlib==3.0.2
    - mccabe==0.6.1
    - mistune==0.8.4
    - msrest==0.6.4
    - msrestazure==0.6.0
    - nbconvert==5.4.0
    - nbformat==4.4.0
    - ndg-httpsclient==0.5.1
    - notebook==5.7.4
    - numpy==1.16.1
    - oauthlib==3.0.1
    - pandocfilters==1.4.2
    - paramiko==2.4.2
    - parso==0.3.3
    - pathspec==0.5.9
    - pexpect==4.6.0
    - pickleshare==0.7.5
    - pillow==5.4.1
    - prometheus-client==0.5.0
    - prompt-toolkit==2.0.8
    - protobuf==3.6.1
    - ptyprocess==0.6.0
    - pyasn1==0.4.5
    - pycparser==2.19
    - pygments==2.3.1
    - pyjwt==1.7.1
    - pylint==2.2.2
    - pynacl==1.3.0
    - pyopenssl==19.0.0
    - pyparsing==2.3.1
    - python-dateutil==2.8.0
    - pytz==2018.9
    - pyyaml==3.13
    - pyzmq==17.1.2
    - qtconsole==4.4.3
    - requests==2.21.0
    - requests-oauthlib==1.2.0
    - ruamel.yaml==0.15.51
    - secretstorage==2.3.1
    - send2trash==1.5.0
    - six==1.12.0
    - tensorboard==1.10.0
    - tensorflow==1.10.0
    - termcolor==1.1.0
    - terminado==0.8.1
    - testpath==0.4.2
    - tornado==5.1.1
    - traitlets==4.3.2
    - typed-ast==1.3.1
    - urllib3==1.23
    - wcwidth==0.1.7
    - webencodings==0.5.1
    - websocket-client==0.54.0
    - werkzeug==0.14.1
    - widgetsnbextension==3.4.2
    - wrapt==1.11.1
